# This is a basic workflow that is manually triggered

name: Push Models-Go

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'gen/models-go/models/v1'
        destination-github-username: 'TapMars'
        destination-repository-name: 'protobuf-models-go'
        target-branch: 'main'
        user-email: 'nmarler@outlook.com'
        commit-message: 'Workflow generated'
